dist: trusty

sudo: required

language: ruby

before_install:
  - echo "before install"

script:
  - echo "test"

  # Install deps.
  - sudo apt update
  - cd ${TRAVIS_BUILD_DIR}
  - bash ci-scripts/linux/install-deps.sh

  # Build all missing boxes.
  - cd ${TRAVIS_BUILD_DIR}/packer
  - packer build ubuntu-mysql.json 
  - packer build ubuntu-storage.json
  - packer build ubuntu-webserver.json 

  # Vagrant up!
  - cd ${TRAVIS_BUILD_DIR}/
  - vagrant up

after_success:
  - echo "after success"
